import type { Metadata } from 'next';

import './globals.css';

import { FC, ReactNode } from 'react';
import {
  Montserrat,
  DM_Serif_Display,
  Poppins,
  Inter,
  Cinzel_Decorative,
} from 'next/font/google';
import { getDictionary, Locale } from './dictionaries';

export const metadata: Metadata = {
  title: 'uniXeven',
  description: 'Generated by create uniXeven app',
};

const cinzelDecorative = Cinzel_Decorative({
  subsets: ['latin'],
  weight: ['700'],
});

const inter = Inter({ subsets: ['latin', 'cyrillic'], weight: '400' });

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
});

const dmSerifDisplay = DM_Serif_Display({
  subsets: ['latin'],
  weight: '400',
  style: ['normal', 'italic'],
});

const poppins = Poppins({ subsets: ['latin'], weight: '400' });

interface RootLayoutProps {
  readonly children: ReactNode;
  params: {
    lang: Locale;
  };
}

const RootLayout: FC<RootLayoutProps> = async ({
  children,
  params: { lang },
}) => {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${montserrat.className} ${dmSerifDisplay.className} ${poppins.className} ${cinzelDecorative.className}  antialiased`}
      >
        {children}
        <div id="modal-portal" />
      </body>
    </html>
  );
};
export default RootLayout;
