import type { Metadata } from 'next';

import './globals.css';
import { Header } from '@/components/Header/Header';
import { FC, ReactNode } from 'react';
import { Montserrat, DM_Serif_Display, Poppins, Inter } from 'next/font/google';
import { getDictionary, Locale } from './dictionaries';

const inter = Inter({ subsets: ['latin'], weight: '400' });
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});
const dmSerifDisplay = DM_Serif_Display({
  subsets: ['latin'],
  weight: '400',
  style: ['normal', 'italic'],
});
const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'uniXeven',
  description: 'Generated by create uniXeven app',
};

interface RootLayoutProps {
  readonly children: ReactNode;
  params: {
    lang: Locale;
  };
}

const RootLayout: FC<RootLayoutProps> = async ({
  children,
  params: { lang },
}) => {
  const { header } = await getDictionary(lang);
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${montserrat.className} ${dmSerifDisplay.className} ${poppins.className} antialiased`}
      >
        <Header nav={header.nav} />
        {children}
        <div id="modal-portal" />
      </body>
    </html>
  );
};
export default RootLayout;
